# Generated by Django 5.0.3 on 2024-03-20 15:24

import core.models.UserManager
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UserManager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idItem', models.AutoField(db_column='id_item', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.CharField(db_column='description', max_length=200)),
                ('price', models.IntegerField(db_column='price')),
                ('image', models.CharField(db_column='image', default='https://womensfitness.co.uk/wp-content/uploads/sites/3/2022/11/Shutterstock_1675475479.jpg?w=900', max_length=500)),
                ('fechaAdicion', models.DateTimeField(auto_now_add=True, db_column='fecha_adicion', verbose_name='Fecha creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='Fecha modificación')),
                ('usuarioAdicion', models.ForeignKey(blank=True, db_column='usuario_adicion', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_adicion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('usuarioModificacion', models.ForeignKey(blank=True, db_column='usuario_modificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificador')),
            ],
            options={
                'db_table': 'MAE_ITEM',
            },
        ),
    ]
